// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB17Nra9Z12lDxUMTNLnRDvbFBIClzsDeI',
    appId: '1:553490222450:web:861e2b850e82915941a1eb',
    messagingSenderId: '553490222450',
    projectId: 'chat-5ebf2',
    authDomain: 'chat-5ebf2.firebaseapp.com',
    storageBucket: 'chat-5ebf2.appspot.com',
    measurementId: 'G-NHRJLVJHY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo3djWrpiBvnUxBOKdsDCDSafWjBqqMx0',
    appId: '1:553490222450:android:d76531202b563c5941a1eb',
    messagingSenderId: '553490222450',
    projectId: 'chat-5ebf2',
    storageBucket: 'chat-5ebf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0e5J-YAken1eCzmYnslwpciCge3VDC5U',
    appId: '1:553490222450:ios:82687e28218305ce41a1eb',
    messagingSenderId: '553490222450',
    projectId: 'chat-5ebf2',
    storageBucket: 'chat-5ebf2.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0e5J-YAken1eCzmYnslwpciCge3VDC5U',
    appId: '1:553490222450:ios:82687e28218305ce41a1eb',
    messagingSenderId: '553490222450',
    projectId: 'chat-5ebf2',
    storageBucket: 'chat-5ebf2.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB17Nra9Z12lDxUMTNLnRDvbFBIClzsDeI',
    appId: '1:553490222450:web:ae24a8e89eb3cddb41a1eb',
    messagingSenderId: '553490222450',
    projectId: 'chat-5ebf2',
    authDomain: 'chat-5ebf2.firebaseapp.com',
    storageBucket: 'chat-5ebf2.appspot.com',
    measurementId: 'G-TY99NB8W4G',
  );
}
